# Site settings
title: Eric Bouchut
url:   //EricBouchut.com # the base hostname (& protocol) for your site
email: contact@EricBouchut.com
description:  "Java developer, Ruby switcher and Ruby on Rails aficionado."
baseurl:   "" # the subpath of your site, e.g. /blog/
timezone:  "Europe/Paris"
permalink: /:year/:month/:day/:title/

# Build settings
markdown: redcarpet
highlighter: pygments
exclude: ["_plugins", "_assets", "_drafts", "Gemfile", "Gemfile.lock", ".ruby-version", ".gitignore"]


# Google Analytics
google_analytics_tracking_id: UA-610695-2

twitter_username: ebouchut
github_username:  ebouchut


#~~~~~~~~~~
# Pinboard: https://github.com/billturner/jekyll-pinboard-tag
#~~~~~~~~~~
pinboard_tag:
  user:       "ebouchut"
  limit:      10

gems:
  - jekyll-sitemap
