site_name: Eric Bouchut

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ebouchut
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ebouchut
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ebouchut
    - icon: fontawesome/brands/mastodon
      link: https://ruby.social/@ebouchut

plugins:
  - search
  - blog:
      blog_toc: true
      post_date_format: long
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
  - tags:
      tags_file: blog/tags.md

nav:
  - Home: index.md
  - Blog: blog/index.md
  - About: blog/about.md
  - Contact: 
      - Contact:  blog/contact.md
      - LinkedIn: https://linkedin.com/in/ebouchut
      - GitHub:   https://github.com/ebouchut
      - Mastodon: https://ruby.social/@ebouchut
      - Twitter:  https://twitter.com/ebouchut
  - Tags: blog/tags.md