site_name: Eric Bouchut

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - blog:
      post_date_format: long
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
  - tags:
      tags_file: blog/tags.md

nav:
  - Home: blog/index.md
  - About: blog/about.md
  - Contact: blog/contact.md
  - Tags: blog/tags.md