[project]
name = "ebouchut-github-io"
version = "0.2.0"
description = "My personal blog"
readme = "README.md"
authors = [
  { name = "Eric Bouchut", email = "ebouchut@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
  "mkdocs >= 1.6.1, <= 1.7",
  "mkdocs-material >= 9.7, < 9.8"
]

[project.urls]
Homepage = "https://EricBouchut.com/"
Documentation = "https://github.com/ebouchut/ebouchut.github.io/?tab=readme-ov-file"
Repository =    "https://github.com/ebouchut/ebouchut.github.io/"
Issues =        "https://github.com/ebouchut/ebouchut.github.io/issues"

[tool.uv]
package = false
